[2016-03-04 09:17:50,581][40708][ERROR][table.py:selectByName:61]: select item from T_DRIVER failed and name = [vvv]
[2016-03-04 09:19:36,021][40708][ERROR][table.py:selectByName:61]: select item from T_DRIVER failed and name = [vvvs]
[2016-03-04 09:22:14,017][40833][INFO][mysql_wrapper.py:_do_use:49]: atrs_test
[2016-03-04 09:22:14,018][40833][DEBUG][mysql_wrapper.py:_init_db:45]: Mysql init success.
[2016-03-04 09:22:14,019][40833][DEBUG][mysql_wrapper.py:close:67]: Close Database: [atrs_test] success.
[2016-03-04 09:23:43,330][40856][INFO][mysql_wrapper.py:_do_use:49]: atrs_test
[2016-03-04 09:23:43,331][40856][DEBUG][mysql_wrapper.py:_init_db:45]: Mysql init success.
[2016-03-04 09:23:43,336][40856][DEBUG][mysql_wrapper.py:close:67]: Close Database: [atrs_test] success.
[2016-03-04 09:34:16,891][40971][INFO][mysql_wrapper.py:_do_use:49]: atrs_test
[2016-03-04 09:34:16,892][40971][DEBUG][mysql_wrapper.py:_init_db:45]: Mysql init success.
[2016-03-04 09:34:16,894][40971][DEBUG][mysql_wrapper.py:close:67]: Close Database: [atrs_test] success.
[2016-03-04 09:35:24,391][40996][INFO][mysql_wrapper.py:_do_use:49]: atrs_test
[2016-03-04 09:35:24,391][40996][DEBUG][mysql_wrapper.py:_init_db:45]: Mysql init success.
[2016-03-04 09:35:24,395][40996][DEBUG][mysql_wrapper.py:close:67]: Close Database: [atrs_test] success.
[2016-03-04 09:35:34,822][41008][INFO][mysql_wrapper.py:_do_use:49]: atrs_test
[2016-03-04 09:35:34,823][41008][DEBUG][mysql_wrapper.py:_init_db:45]: Mysql init success.
[2016-03-04 09:35:34,823][41008][DEBUG][mysql_wrapper.py:close:67]: Close Database: [atrs_test] success.
[2016-03-04 11:26:53,662][42551][INFO][mysql_wrapper.py:_do_use:49]: atrs_test
[2016-03-04 11:26:53,663][42551][DEBUG][mysql_wrapper.py:_init_db:45]: Mysql init success.
[2016-03-04 11:26:53,664][42551][DEBUG][mysql_wrapper.py:close:67]: Close Database: [atrs_test] success.
[2016-03-06 20:57:53,681][47905][ERROR][table.py:insert:81]: duplicate data in T_CASE [aaaaaaa]
