[2015-12-28 19:14:31,463][10432][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-28 19:14:31,464][10432][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-28 19:14:31,464][10432][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER  where  name = "tttttt"    limit 0,1;
[2015-12-28 19:14:31,520][10432][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: insert into T_DRIVER(name,teardown,setup,param,exex,description) values ("tttttt","print 'teardown!'
","print 'setup!'
","{'a': 2, 'duedata': 14, 'b': 7}","assert (self.a*self.b == self.duedata)","mutiply driver");
[2015-12-28 19:14:31,523][10432][ERROR][mysql_wrapper.py:execute:77]: Execute line: [insert into T_DRIVER(name,teardown,setup,param,exex,description) values ("tttttt","print 'teardown!'
","print 'setup!'
","{'a': 2, 'duedata': 14, 'b': 7}","assert (self.a*self.b == self.duedata)","mutiply driver"); ...] failed.
[2015-12-28 19:14:31,523][10432][ERROR][mysql_wrapper.py:execute:80]: Traceback (most recent call last):
  File "/Users/wangming/workspace/atrs/db/mysql_wrapper.py", line 72, in execute
    self.cursor.execute(line)
  File "/Library/Python/2.7/site-packages/mysql/connector/cursor.py", line 515, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/Library/Python/2.7/site-packages/mysql/connector/connection.py", line 488, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/Library/Python/2.7/site-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
ProgrammingError: 1054 (42S22): Unknown column 'teardown' in 'field list'

[2015-12-28 19:14:31,523][10432][ERROR][mysql_wrapper.py:insert_row:159]: Insert row into table: T_DRIVER failed.
[2015-12-28 19:14:31,527][10432][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-28 19:15:58,886][10465][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-28 19:15:58,887][10465][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-28 19:15:58,887][10465][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER  where  name = "tttttt"    limit 0,1;
[2015-12-28 19:15:58,888][10465][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: insert into T_DRIVER(name,teardown,setup,param,exex,description) values ("tttttt","print 'teardown!'
","print 'setup!'
","{'a': 2, 'duedata': 14, 'b': 7}","assert (self.a*self.b == self.duedata)","mutiply driver");
[2015-12-28 19:15:58,888][10465][ERROR][mysql_wrapper.py:execute:77]: Execute line: [insert into T_DRIVER(name,teardown,setup,param,exex,description) values ("tttttt","print 'teardown!'
","print 'setup!'
","{'a': 2, 'duedata': 14, 'b': 7}","assert (self.a*self.b == self.duedata)","mutiply driver"); ...] failed.
[2015-12-28 19:15:58,889][10465][ERROR][mysql_wrapper.py:execute:80]: Traceback (most recent call last):
  File "/Users/wangming/workspace/atrs/db/mysql_wrapper.py", line 72, in execute
    self.cursor.execute(line)
  File "/Library/Python/2.7/site-packages/mysql/connector/cursor.py", line 515, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/Library/Python/2.7/site-packages/mysql/connector/connection.py", line 488, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/Library/Python/2.7/site-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
ProgrammingError: 1054 (42S22): Unknown column 'teardown' in 'field list'

[2015-12-28 19:15:58,889][10465][ERROR][mysql_wrapper.py:insert_row:159]: Insert row into table: T_DRIVER failed.
[2015-12-28 19:15:58,893][10465][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-28 19:16:34,776][10475][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-28 19:16:34,776][10475][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-28 19:16:34,776][10475][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER  where  name = "tttttt"    limit 0,1;
[2015-12-28 19:16:34,777][10475][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: insert into T_DRIVER(name,teardown,setup,param,exex,description) values ("tttttt","print 'teardown!'
","print 'setup!'
","{'a': 2, 'duedata': 14, 'b': 7}","assert (self.a*self.b == self.duedata)","mutiply driver");
[2015-12-28 19:16:34,777][10475][ERROR][mysql_wrapper.py:execute:77]: Execute line: [insert into T_DRIVER(name,teardown,setup,param,exex,description) values ("tttttt","print 'teardown!'
","print 'setup!'
","{'a': 2, 'duedata': 14, 'b': 7}","assert (self.a*self.b == self.duedata)","mutiply driver"); ...] failed.
[2015-12-28 19:16:34,778][10475][ERROR][mysql_wrapper.py:execute:80]: Traceback (most recent call last):
  File "/Users/wangming/workspace/atrs/db/mysql_wrapper.py", line 72, in execute
    self.cursor.execute(line)
  File "/Library/Python/2.7/site-packages/mysql/connector/cursor.py", line 515, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/Library/Python/2.7/site-packages/mysql/connector/connection.py", line 488, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/Library/Python/2.7/site-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
ProgrammingError: 1054 (42S22): Unknown column 'teardown' in 'field list'

[2015-12-28 19:16:34,778][10475][ERROR][mysql_wrapper.py:insert_row:159]: Insert row into table: T_DRIVER failed.
[2015-12-28 19:16:34,784][10475][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-28 19:18:06,079][10486][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-28 19:18:06,079][10486][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-28 19:18:06,079][10486][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER  where  name = "tttttt"    limit 0,1;
[2015-12-28 19:18:06,080][10486][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: insert into T_DRIVER(name,teardown,setup,param,exex,description) values ("tttttt","print 'teardown!'
","print 'setup!'
","{'a': 2, 'duedata': 14, 'b': 7}","assert (self.a*self.b == self.duedata)","mutiply driver");
[2015-12-28 19:18:06,080][10486][ERROR][mysql_wrapper.py:execute:77]: Execute line: [insert into T_DRIVER(name,teardown,setup,param,exex,description) values ("tttttt","print 'teardown!'
","print 'setup!'
","{'a': 2, 'duedata': 14, 'b': 7}","assert (self.a*self.b == self.duedata)","mutiply driver"); ...] failed.
[2015-12-28 19:18:06,081][10486][ERROR][mysql_wrapper.py:execute:80]: Traceback (most recent call last):
  File "/Users/wangming/workspace/atrs/db/mysql_wrapper.py", line 72, in execute
    self.cursor.execute(line)
  File "/Library/Python/2.7/site-packages/mysql/connector/cursor.py", line 515, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/Library/Python/2.7/site-packages/mysql/connector/connection.py", line 488, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/Library/Python/2.7/site-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
ProgrammingError: 1054 (42S22): Unknown column 'teardown' in 'field list'

[2015-12-28 19:18:06,081][10486][ERROR][mysql_wrapper.py:insert_row:159]: Insert row into table: T_DRIVER failed.
[2015-12-28 19:18:06,085][10486][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-28 19:18:32,084][10497][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-28 19:18:32,085][10497][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-28 19:18:32,085][10497][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER  where  name = "tttttt"    limit 0,1;
[2015-12-28 19:18:32,086][10497][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: insert into T_DRIVER(name,teardown,setup,param,exex,description) values ("tttttt","print 'teardown!'
","print 'setup!'
","{'a': 2, 'duedata': 14, 'b': 7}","assert (self.a*self.b == self.duedata)","mutiply driver");
[2015-12-28 19:18:32,086][10497][ERROR][mysql_wrapper.py:execute:77]: Execute line: [insert into T_DRIVER(name,teardown,setup,param,exex,description) values ("tttttt","print 'teardown!'
","print 'setup!'
","{'a': 2, 'duedata': 14, 'b': 7}","assert (self.a*self.b == self.duedata)","mutiply driver"); ...] failed.
[2015-12-28 19:18:32,087][10497][ERROR][mysql_wrapper.py:execute:80]: Traceback (most recent call last):
  File "/Users/wangming/workspace/atrs/db/mysql_wrapper.py", line 72, in execute
    self.cursor.execute(line)
  File "/Library/Python/2.7/site-packages/mysql/connector/cursor.py", line 515, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/Library/Python/2.7/site-packages/mysql/connector/connection.py", line 488, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/Library/Python/2.7/site-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
ProgrammingError: 1054 (42S22): Unknown column 'teardown' in 'field list'

[2015-12-28 19:18:32,087][10497][ERROR][mysql_wrapper.py:insert_row:159]: Insert row into table: T_DRIVER failed.
[2015-12-28 19:18:32,087][10497][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER where id = 1;
[2015-12-28 19:18:32,114][10497][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: show fields from T_DRIVER ;
[2015-12-28 19:18:32,133][10497][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-28 19:23:09,225][10514][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-28 19:23:09,226][10514][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-28 19:23:09,226][10514][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER  where  name = "tttttt"    limit 0,1;
[2015-12-28 19:23:09,227][10514][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: insert into T_DRIVER(name,teardown,setup,param,exex,description) values ("tttttt","print 'teardown!'
","print 'setup!'
","{'a': 2, 'duedata': 14, 'b': 7}","assert (self.a*self.b == self.duedata)","mutiply driver");
[2015-12-28 19:23:09,227][10514][ERROR][mysql_wrapper.py:execute:77]: Execute line: [insert into T_DRIVER(name,teardown,setup,param,exex,description) values ("tttttt","print 'teardown!'
","print 'setup!'
","{'a': 2, 'duedata': 14, 'b': 7}","assert (self.a*self.b == self.duedata)","mutiply driver"); ...] failed.
[2015-12-28 19:23:09,228][10514][ERROR][mysql_wrapper.py:execute:80]: Traceback (most recent call last):
  File "/Users/wangming/workspace/atrs/db/mysql_wrapper.py", line 72, in execute
    self.cursor.execute(line)
  File "/Library/Python/2.7/site-packages/mysql/connector/cursor.py", line 515, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/Library/Python/2.7/site-packages/mysql/connector/connection.py", line 488, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/Library/Python/2.7/site-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
ProgrammingError: 1054 (42S22): Unknown column 'teardown' in 'field list'

[2015-12-28 19:23:09,228][10514][ERROR][mysql_wrapper.py:insert_row:159]: Insert row into table: T_DRIVER failed.
[2015-12-28 19:23:09,228][10514][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER where id = 1;
[2015-12-28 19:23:09,229][10514][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: show fields from T_DRIVER ;
[2015-12-28 19:23:09,255][10514][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER     limit 1,2;
[2015-12-28 19:23:09,256][10514][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: show fields from T_DRIVER ;
[2015-12-28 19:23:09,257][10514][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select count(*) from T_DRIVER 
[2015-12-28 19:23:09,269][10514][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-28 19:25:59,665][10527][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-28 19:25:59,666][10527][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-28 19:25:59,666][10527][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER  where  name = "tttttt"    limit 0,1;
[2015-12-28 19:25:59,667][10527][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: insert into T_DRIVER(name,teardown,setup,param,exex,description) values ("tttttt","print 'teardown!'
","print 'setup!'
","{'a': 2, 'duedata': 14, 'b': 7}","assert (self.a*self.b == self.duedata)","mutiply driver");
[2015-12-28 19:25:59,667][10527][ERROR][mysql_wrapper.py:execute:77]: Execute line: [insert into T_DRIVER(name,teardown,setup,param,exex,description) values ("tttttt","print 'teardown!'
","print 'setup!'
","{'a': 2, 'duedata': 14, 'b': 7}","assert (self.a*self.b == self.duedata)","mutiply driver"); ...] failed.
[2015-12-28 19:25:59,668][10527][ERROR][mysql_wrapper.py:execute:80]: Traceback (most recent call last):
  File "/Users/wangming/workspace/atrs/db/mysql_wrapper.py", line 72, in execute
    self.cursor.execute(line)
  File "/Library/Python/2.7/site-packages/mysql/connector/cursor.py", line 515, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/Library/Python/2.7/site-packages/mysql/connector/connection.py", line 488, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/Library/Python/2.7/site-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
ProgrammingError: 1054 (42S22): Unknown column 'teardown' in 'field list'

[2015-12-28 19:25:59,668][10527][ERROR][mysql_wrapper.py:insert_row:159]: Insert row into table: T_DRIVER failed.
[2015-12-28 19:25:59,668][10527][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER where id = 1;
[2015-12-28 19:25:59,669][10527][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: show fields from T_DRIVER ;
[2015-12-28 19:25:59,694][10527][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER     limit 0,2;
[2015-12-28 19:25:59,695][10527][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: show fields from T_DRIVER ;
[2015-12-28 19:25:59,697][10527][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select count(*) from T_DRIVER 
[2015-12-28 19:25:59,703][10527][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-28 19:28:42,459][10550][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-28 19:28:42,459][10550][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-28 19:28:42,459][10550][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER  where  name = "tttttt"    limit 0,1;
[2015-12-28 19:28:42,460][10550][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: insert into T_DRIVER(name,teardown,setup,param,exex,description) values ("tttttt","print 'teardown!'
","print 'setup!'
","{'a': 2, 'duedata': 14, 'b': 7}","assert (self.a*self.b == self.duedata)","mutiply driver");
[2015-12-28 19:28:42,460][10550][ERROR][mysql_wrapper.py:execute:77]: Execute line: [insert into T_DRIVER(name,teardown,setup,param,exex,description) values ("tttttt","print 'teardown!'
","print 'setup!'
","{'a': 2, 'duedata': 14, 'b': 7}","assert (self.a*self.b == self.duedata)","mutiply driver"); ...] failed.
[2015-12-28 19:28:42,461][10550][ERROR][mysql_wrapper.py:execute:80]: Traceback (most recent call last):
  File "/Users/wangming/workspace/atrs/db/mysql_wrapper.py", line 72, in execute
    self.cursor.execute(line)
  File "/Library/Python/2.7/site-packages/mysql/connector/cursor.py", line 515, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/Library/Python/2.7/site-packages/mysql/connector/connection.py", line 488, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/Library/Python/2.7/site-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
ProgrammingError: 1054 (42S22): Unknown column 'teardown' in 'field list'

[2015-12-28 19:28:42,461][10550][ERROR][mysql_wrapper.py:insert_row:159]: Insert row into table: T_DRIVER failed.
[2015-12-28 19:28:42,462][10550][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER where id = 1;
[2015-12-28 19:28:42,462][10550][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: show fields from T_DRIVER ;
[2015-12-28 19:28:42,487][10550][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER     limit 0,2;
[2015-12-28 19:28:42,487][10550][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: show fields from T_DRIVER ;
[2015-12-28 19:28:42,493][10550][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select count(*) from T_DRIVER 
[2015-12-28 19:28:42,501][10550][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-28 19:29:00,478][10560][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-28 19:29:00,478][10560][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-28 19:29:00,478][10560][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER     limit 0,2;
[2015-12-28 19:29:00,479][10560][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: show fields from T_DRIVER ;
[2015-12-28 19:29:00,499][10560][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select count(*) from T_DRIVER 
[2015-12-28 19:29:00,503][10560][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-28 19:29:19,133][10570][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-28 19:29:19,134][10570][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-28 19:29:19,134][10570][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER     limit 0,2;
[2015-12-28 19:29:19,135][10570][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: show fields from T_DRIVER ;
[2015-12-28 19:29:19,153][10570][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER     limit 0,2;
[2015-12-28 19:29:19,154][10570][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: show fields from T_DRIVER ;
[2015-12-28 19:29:19,160][10570][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select count(*) from T_DRIVER 
[2015-12-28 19:29:19,164][10570][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-28 19:29:27,988][10580][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-28 19:29:27,988][10580][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-28 19:29:27,989][10580][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER     limit 0,2;
[2015-12-28 19:29:27,989][10580][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: show fields from T_DRIVER ;
[2015-12-28 19:29:28,009][10580][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER     limit 1,2;
[2015-12-28 19:29:28,009][10580][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: show fields from T_DRIVER ;
[2015-12-28 19:29:28,016][10580][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select count(*) from T_DRIVER 
[2015-12-28 19:29:28,020][10580][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-28 19:30:17,224][10592][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-28 19:30:17,225][10592][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-28 19:30:17,225][10592][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER     limit 0,2;
[2015-12-28 19:30:17,225][10592][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: show fields from T_DRIVER ;
[2015-12-28 19:30:17,245][10592][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER     limit 1,2;
[2015-12-28 19:30:17,245][10592][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: show fields from T_DRIVER ;
[2015-12-28 19:30:17,252][10592][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select count(*) from T_DRIVER 
[2015-12-28 19:30:17,256][10592][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-28 19:34:39,917][10617][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-28 19:34:39,917][10617][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-28 19:34:39,917][10617][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER     limit 0,2;
[2015-12-28 19:34:39,919][10617][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: show fields from T_DRIVER ;
[2015-12-28 19:34:39,932][10617][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER     limit 1,2;
[2015-12-28 19:34:39,934][10617][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: show fields from T_DRIVER ;
[2015-12-28 19:34:39,935][10617][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select count(*) from T_DRIVER 
[2015-12-28 19:34:39,939][10617][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-28 19:37:02,315][10628][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-28 19:37:02,316][10628][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-28 19:37:02,316][10628][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER  where  name = "tttttt"    limit 0,1;
[2015-12-28 19:37:02,323][10628][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: insert into T_DRIVER(teardownpy,name,setuppy,param,execpy,description) values ("print 'teardown!'
","tttttt","print 'setup!'
","{'a': 2, 'duedata': 14, 'b': 7}","assert (self.a*self.b == self.duedata)","mutiply driver");
[2015-12-28 19:37:02,361][10628][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select count(*) from T_DRIVER 
[2015-12-28 19:37:02,368][10628][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-29 10:38:14,715][13070][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-29 10:38:14,716][13070][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-29 10:38:14,716][13070][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER  where  name = "tttttt"    limit 0,1;
[2015-12-29 10:38:14,717][13070][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: insert into T_DRIVER(teardownpy,name,setuppy,param,execpy,description) values ("print \'teardown!\'
","tttttt","print \'setup!\'
","{\'a\': 2, \'duedata\': 14, \'b\': 7}","assert (self.a*self.b == self.duedata)","mutiply driver");
[2015-12-29 10:38:14,749][13070][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select count(*) from T_DRIVER 
[2015-12-29 10:38:14,754][13070][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-29 10:38:32,745][13081][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-29 10:38:32,745][13081][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-29 10:38:32,746][13081][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER  where  name = "tttttt"    limit 0,1;
[2015-12-29 10:38:32,746][13081][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: show fields from T_DRIVER ;
[2015-12-29 10:38:32,766][13081][ERROR][table.py:insert:124]: duplicate data in T_DRIVER [tttttt]
[2015-12-29 10:38:32,766][13081][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select count(*) from T_DRIVER 
[2015-12-29 10:38:32,770][13081][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-29 10:38:41,663][13092][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-29 10:38:41,663][13092][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-29 10:38:41,663][13092][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER  where  name = "t2"    limit 0,1;
[2015-12-29 10:38:41,668][13092][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-29 10:38:55,710][13102][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-29 10:38:55,710][13102][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-29 10:38:55,711][13102][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER  where  name = "tttttt"    limit 0,1;
[2015-12-29 10:38:55,711][13102][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: show fields from T_DRIVER ;
[2015-12-29 10:38:55,731][13102][ERROR][table.py:insert:124]: duplicate data in T_DRIVER [tttttt]
[2015-12-29 10:38:55,731][13102][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select count(*) from T_DRIVER 
[2015-12-29 10:38:55,736][13102][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-29 10:39:11,245][13112][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-29 10:39:11,246][13112][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-29 10:39:11,246][13112][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER  where  name = "t2"    limit 0,1;
[2015-12-29 10:39:11,247][13112][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: insert into T_DRIVER(teardownpy,name,setuppy,param,execpy,description) values ("print \'teardown!\'
","t2","print \'setup!\'
","{\'a\': 2, \'duedata\': 14, \'b\': 7}","assert (self.a*self.b == self.duedata)","mutiply driver");
[2015-12-29 10:39:11,253][13112][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select count(*) from T_DRIVER 
[2015-12-29 10:39:11,258][13112][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-29 10:39:42,203][13122][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-29 10:39:42,204][13122][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-29 10:39:42,204][13122][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER  where  name = "t2"    limit 0,1;
[2015-12-29 10:39:42,205][13122][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: show fields from T_DRIVER ;
[2015-12-29 10:39:42,217][13122][ERROR][table.py:insert:124]: duplicate data in T_DRIVER [t2]
[2015-12-29 10:39:42,218][13122][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select count(*) from T_DRIVER 
[2015-12-29 10:39:42,221][13122][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-29 10:39:47,507][13132][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-29 10:39:47,507][13132][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-29 10:39:47,508][13132][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER  where  name = "t3"    limit 0,1;
[2015-12-29 10:39:47,508][13132][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: insert into T_DRIVER(teardownpy,name,setuppy,param,execpy,description) values ("print \'teardown!\'
","t3","print \'setup!\'
","{\'a\': 2, \'duedata\': 14, \'b\': 7}","assert (self.a*self.b == self.duedata)","mutiply driver");
[2015-12-29 10:39:47,515][13132][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select count(*) from T_DRIVER 
[2015-12-29 10:39:47,520][13132][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-29 10:45:06,408][13225][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-29 10:45:06,409][13225][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-29 10:45:06,413][13225][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-29 10:45:29,716][13237][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-29 10:45:29,716][13237][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-29 10:45:29,717][13237][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER  where  name = "t3"    limit 0,1;
[2015-12-29 10:45:29,744][13237][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: show fields from T_DRIVER ;
[2015-12-29 10:45:29,766][13237][ERROR][table.py:insert:125]: duplicate data in T_DRIVER [t3]
[2015-12-29 10:45:29,766][13237][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select count(*) from T_DRIVER 
[2015-12-29 10:45:29,779][13237][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-29 10:45:37,603][13248][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-29 10:45:37,603][13248][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-29 10:45:37,603][13248][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER  where  name = "t4"    limit 0,1;
[2015-12-29 10:45:37,604][13248][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: insert into T_DRIVER(teardownpy,name,setuppy,param,execpy,description) values ("print \'teardown!\'
","t4","print \'setup!\'
","{\"a\": 2, \"duedata\": 14, \"b\": 7}","assert (self.a*self.b == self.duedata)","mutiply driver");
[2015-12-29 10:45:37,628][13248][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select count(*) from T_DRIVER 
[2015-12-29 10:45:37,633][13248][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-29 10:46:45,884][13260][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-29 10:46:45,884][13260][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-29 10:46:45,884][13260][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER  where  name = "t5"    limit 0,1;
[2015-12-29 10:46:45,885][13260][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: insert into T_DRIVER(teardownpy,name,setuppy,param,execpy,description) values ("print 'teardown!'
","t5","print 'setup!'
","{"a": 2, "duedata": 14, "b": 7}","assert (self.a*self.b == self.duedata)","mutiply driver");
[2015-12-29 10:46:45,896][13260][ERROR][mysql_wrapper.py:execute:77]: Execute line: [insert into T_DRIVER(teardownpy,name,setuppy,param,execpy,description) values ("print 'teardown!'
","t5","print 'setup!'
","{"a": 2, "duedata": 14, "b": 7}","assert (self.a*self.b == self.duedata)","mutiply driver"); ...] failed.
[2015-12-29 10:46:45,898][13260][ERROR][mysql_wrapper.py:execute:80]: Traceback (most recent call last):
  File "/Users/wangming/workspace/atrs/db/mysql_wrapper.py", line 72, in execute
    self.cursor.execute(line)
  File "/Library/Python/2.7/site-packages/mysql/connector/cursor.py", line 515, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/Library/Python/2.7/site-packages/mysql/connector/connection.py", line 488, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/Library/Python/2.7/site-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'a": 2, "duedata": 14, "b": 7}","assert (self.a*self.b == self.duedata)","mutiply' at line 1

[2015-12-29 10:46:45,898][13260][ERROR][mysql_wrapper.py:insert_row:159]: Insert row into table: T_DRIVER failed.
[2015-12-29 10:46:45,899][13260][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select count(*) from T_DRIVER 
[2015-12-29 10:46:45,903][13260][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-29 10:47:42,930][13270][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-29 10:47:42,930][13270][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-29 10:47:42,930][13270][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER  where  name = "t5"    limit 0,1;
[2015-12-29 10:47:42,931][13270][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: insert into T_DRIVER(teardownpy,name,setuppy,param,execpy,description) values ("print 'teardown!'
","t5","print 'setup!'
","{"a": 2, "duedata": 14, "b": 7}","assert (self.a*self.b == self.duedata)","mutiply driver");
[2015-12-29 10:47:42,931][13270][ERROR][mysql_wrapper.py:execute:77]: Execute line: [insert into T_DRIVER(teardownpy,name,setuppy,param,execpy,description) values ("print 'teardown!'
","t5","print 'setup!'
","{"a": 2, "duedata": 14, "b": 7}","assert (self.a*self.b == self.duedata)","mutiply driver"); ...] failed.
[2015-12-29 10:47:42,932][13270][ERROR][mysql_wrapper.py:execute:80]: Traceback (most recent call last):
  File "/Users/wangming/workspace/atrs/db/mysql_wrapper.py", line 72, in execute
    self.cursor.execute(line)
  File "/Library/Python/2.7/site-packages/mysql/connector/cursor.py", line 515, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/Library/Python/2.7/site-packages/mysql/connector/connection.py", line 488, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/Library/Python/2.7/site-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'a": 2, "duedata": 14, "b": 7}","assert (self.a*self.b == self.duedata)","mutiply' at line 1

[2015-12-29 10:47:42,932][13270][ERROR][mysql_wrapper.py:insert_row:159]: Insert row into table: T_DRIVER failed.
[2015-12-29 10:47:42,932][13270][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select count(*) from T_DRIVER 
[2015-12-29 10:47:42,945][13270][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
[2015-12-29 10:48:42,762][13284][INFO][mysql_wrapper.py:_do_use:48]: atrs_test
[2015-12-29 10:48:42,762][13284][DEBUG][mysql_wrapper.py:_init_db:44]: Mysql init success.
[2015-12-29 10:48:42,763][13284][DEBUG][mysql_wrapper.py:execute:71]: execute cmd: select * from T_DRIVER  where  name = "t5"    limit 0,1;
[2015-12-29 10:48:42,768][13284][DEBUG][mysql_wrapper.py:close:66]: Close Database: [atrs_test] success.
